### ISSUE TITLE
error on fedora

### ISSUE THREAD

**Issue by texrg** [ruby-numo/gnuplot#16]
require "numo/gnuplot"
=> true
irb(main):006:0> Numo.gnuplot do
irb(main):007:1*   set title:"Example Plot"
irb(main):008:1>   plot "sin(x)",w:"lines"
irb(main):009:1> end
Errno::ENOENT: No such file or directory - gnuplot
from /home/user/.gem/ruby/gems/numo-gnuplot-0.2.4/lib/numo/gnuplot.rb:59:in `popen'
....

**Comment by masa16** [comment]
Have you installed gnuplot?

**Comment by masa16** [comment]
Seems not an issue of numo-gnuplot.
