### ISSUE TITLE
SVG may take a long time to display in IRuby in a browser

### ISSUE THREAD

**Issue by kojix2** [ruby-numo/gnuplot#19]
If you try to display a scatter plot of data that contains a large number of samples, the browser may freeze. 
```ruby
Numo.noteplot
  plot SomeBigData
end
```
In this case, he PNG format may be more appropriate than the SVG format.

Of course, the SVG format is good for displaying small sized data. 
So there is no best format for every situation. 

One solution is to be able to specify the format.

```ruby
Numo.noteplot
  set :term, :png
  plot SomeBigData
end

Numo.noteplot(format: :png)
  plot SomeBigData
end

Numo::Noteplot.set_format :png

etc...
```

But I do not know if this is really good.

**Comment by kojix2** [comment]
This is a lazy way
```ruby
Numo.gnuplot
  set :term, :png
  set :output, "hoge.png"
  plot SomeBigData
end
open "hoge.png"
```

**Comment by zheng-yongping** [comment]
@kojix2 
'pngcairo' may be best terminal type for every situation.

pngcairo:
![image](https://user-images.githubusercontent.com/55312951/65010065-45e13700-d941-11e9-875a-36bbdbc83158.png)

png:
![image](https://user-images.githubusercontent.com/55312951/65009966-0c103080-d941-11e9-825b-b6c0acad9d8d.png)

**Comment by kojix2** [comment]
This issue is old and will be closed.
When I think about it, this is not a problem that should be handled on the numo-narray side. My bad.
