### ISSUE TITLE
Thanks for the gem!

### ISSUE THREAD

**Issue by ghost** [ruby-numo/gnuplot#2]
Hello there Masahiro Tanaka,

This is not an "issue request" but a "thank you" note.

I have been needing a ruby-wrapper towards gnuplot for a longer while. I just discovered your gem here and I am currently exploring it. You added quite many examples already so I hope I can learn from them, especially with a pretty ruby-like API.

It works fine so far:
  http://shevegen.square7.ch/GNUPLOT_AND_RUBY.png

I hope to eventually use the ruby wrapper in order to auto-generate some GNUPLOT datasets, in particular for some statistical dataset.

Feel free to close the issue here, I just wanted to write a comment of appreciation - hopefully you can add even more examples in the future over the next years; examples help me a lot.

Thanks.

**Comment by masa16** [comment]
I appreciate your message.
